datasets:
  ood_manual_mild:
  - label: policy_0
    path: /mnt/data/output/data/ood_manual/mild_variants/policy_0
  - label: policy_1
    path: /mnt/data/output/data/ood_manual/mild_variants/policy_1
max_samples: 5000
rollout:
  batch_size: 32
  device: auto
  horizon: 16
  num_workers: 0
  split: test
