datasets:
  baseline: ''
  ood_splits: {}
logging:
  log_level: INFO
  output_dir: output/eval
max_samples: 5000
metrics:
  ade_fde: true
  collisions: true
  invariance: true
  smoothness: true
  wasserstein: true
rollout:
  batch_size: 32
  device: auto
  horizon: 16
  num_workers: 0
  split: test
seeds:
- 3
