seed: 19
device: auto
log_interval: 50
validate_interval: 2000
epochs: 70
batch_size: 32
num_workers: 4
latent_dim:
  global: 32
  local: 16
window_len: 6
max_grad_norm: 5.0
optimizer:
  lr: 0.00025
  betas: [0.9, 0.999]
  weight_decay: 0.0
scheduler:
  warmup_steps: 2500
  min_lr: 1.0e-5
model:
  encoder_dim: 256
  encoder_layers: 4
  encoder_heads: 4
  decoder_layers: 3
  dropout: 0.1
  action_dim: 2
  agents: 1
  teams: 2
  state_dim: 4
  sequence_length: 16
  reconstruction_loss: smooth_l1
paths:
  data_root: output/data
  run_dir: output/runs/hier_cvae
